receiver:
    port: 38787
    socketBacklog: 1024
    socketSendBufferSize: 2097152 # 2M
    socketReceiveBufferSize: 2097152 # 2M
    # 1.RANDOM 2.ROUND_ROBIN 3.HASH
    dispatcherStrategy: "RANDOM"
    freeMsgAsyncQueueSize: 2097152 # 2^21
    logDispatcherQueueSize: 65536

sseServer:
    port: 30081
    maxConcurrentLogStream: 65536

log:
    logPath: "/var/logs/logstash-hub/"
    maxSingleLogSize: "2 GB"
    maxAccumulatedLogSize: "20 GB"
    # ISO-8601 Durations
    maxLastModified: "P60D"
    maxCountOfCompressedPerHour: 16

